# Generated by Django 5.0.3 on 2024-04-29 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0004_alter_logintable_id_alter_usertable_id'),
        ('userapp', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.usertable'),
        ),
    ]
