# Generated by Django 5.0.3 on 2024-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
