# Generated by Django 5.0.3 on 2024-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_alter_logintable_id_alter_usertable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
